export const ExceptionTitleList = {
  NotFound: 'Not Found',
  Forbidden: 'Forbidden',
  Unauthorized: 'Unauthorized',
  IncorrectPassword: 'IncorrectPassword',
  UserInactive: 'User is not Active',
  BadRequest: 'BadRequest',
  InvalidCredentials: 'InvalidCredentials',
  DeleteDefaultError: 'DeleteDefaultError',
  TokenExpired: 'TokenExpired',
  TooManyTries: 'TooManyTries',
  InvalidRequest: 'Invalid Request',
  UserNotFound: 'User not found',
  InvalidOTP: 'Invalid OTP',
  InvalidOTPStatus: 'Invalid OTP Status',
  UserAlreadyExists: 'User already exists',
  DefaultError: 'Something went wrong. Please try again later.',
} as const;
